version: "3"
services:
  actordb1:
    image: bytepixie/actordb:${ACTORDB_VERSION:-latest}
    environment:
      ##
      ## actordb user's UserID and GroupID
      ##
      - NEW_UID
      - NEW_GID
    ports:
      - "33316:33306"
      - "33317:33307"
    volumes:
      - "./node1/data:/var/lib/actordb"
      - "./node1/etc:/etc/actordb"
      - "./node1/logs:/var/log/actordb"
    networks:
      default:
        aliases:
          - actordb1.local

  actordb2:
    image: bytepixie/actordb:${ACTORDB_VERSION:-latest}
    environment:
      ##
      ## actordb user's UserID and GroupID
      ##
      - NEW_UID
      - NEW_GID
    ports:
      - "33326:33306"
      - "33327:33307"
    volumes:
      - "./node2/data:/var/lib/actordb"
      - "./node2/etc:/etc/actordb"
      - "./node2/logs:/var/log/actordb"
    links:
      - actordb1
    networks:
      default:
        aliases:
          - actordb2.local

  actordb3:
    image: bytepixie/actordb:${ACTORDB_VERSION:-latest}
    environment:
      ##
      ## actordb user's UserID and GroupID
      ##
      - NEW_UID
      - NEW_GID
    ports:
      - "33336:33306"
      - "33337:33307"
    volumes:
      - "./node3/data:/var/lib/actordb"
      - "./node3/etc:/etc/actordb"
      - "./node3/logs:/var/log/actordb"
    links:
      - actordb1
    networks:
      default:
        aliases:
          - actordb3.local

  #
  # A single node per machine service, config in .env.
  #
  actordb:
    image: bytepixie/actordb:${ACTORDB_VERSION:-latest}
    environment:
      ##
      ## actordb user's UserID and GroupID
      ##
      - NEW_UID
      - NEW_GID
      - ACTORDB_NODE=${ACTORDB_NODE:-actordb@actordb.local}
    ports:
      - "${ACTORDB_PORT_THRIFT:-33306}:33306"
      - "${ACTORDB_PORT_MYSQL:-33307}:33307"
    volumes:
      - "${ACTORDB_DATA:-./actordb-data}:/var/lib/actordb"
#      - "${ACTORDB_ETC:-./actordb-etc}:/etc/actordb"
      - "${ACTORDB_LOGS:-./actordb-logs}:/var/log/actordb"

networks:
  default:
